# Generated by Django 4.2.13 on 2024-07-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=48, null=True)),
                ('core_hour', models.CharField(max_length=48, null=True)),
                ('year', models.CharField(max_length=48, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.CharField(max_length=48, null=True)),
                ('pf_no', models.CharField(max_length=48, null=True)),
            ],
        ),
    ]
