# Generated by Django 4.2.13 on 2024-06-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HARS.mailsetting'),
        ),
    ]
