# Generated by Django 4.2.13 on 2024-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0002_corehour_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email_sent',
            field=models.BooleanField(default=True),
        ),
    ]
