# Generated by Django 4.2.13 on 2024-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0002_alter_mail_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=32)),
                ('rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
