# Generated by Django 4.2.13 on 2024-06-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0003_quarterlyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
