# Generated by Django 4.2.13 on 2024-07-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0003_application_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
