# Generated by Django 4.2.13 on 2024-06-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0004_application_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='screenshot',
            field=models.BooleanField(default=False),
        ),
    ]
