# Generated by Django 4.2.13 on 2024-07-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0004_alter_application_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
