# Generated by Django 4.2.13 on 2024-06-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0005_application_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='screenshot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='harsdates',
            name='value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
