# Generated by Django 4.2.13 on 2024-07-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0005_application_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='budget_head',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='project_no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
