# Generated by Django 4.2 on 2024-07-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0006_alter_application_screenshot_alter_harsdates_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='cc',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
