# Generated by Django 4.2 on 2024-08-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0007_alter_application_budget_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_no',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pi_name',
            field=models.CharField(max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pi_type',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
