# Generated by Django 4.2 on 2024-08-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0008_remove_project_project_no_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
