# Generated by Django 4.2 on 2024-08-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0009_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('pf_no', 'project_name')},
        ),
    ]
