# Generated by Django 4.2.13 on 2024-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0010_alter_project_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
