# Generated by Django 4.2.13 on 2024-09-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0011_topup_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='email_sent',
        ),
    ]
