# Generated by Django 4.2 on 2024-10-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0012_remove_topup_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pool_allocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topup',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topup',
            name='pool_allocation',
            field=models.BooleanField(default=False),
        ),
    ]
