# Generated by Django 4.2 on 2024-10-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0013_application_pool_allocation_topup_email_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='user_account',
        ),
        migrations.AddField(
            model_name='topup',
            name='account_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='HARS.accounttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup',
            name='hpc_profile',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='HARS.hpcprofile'),
            preserve_default=False,
        ),
    ]
