# Generated by Django 4.2 on 2024-10-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0014_remove_topup_user_account_topup_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='topup',
            name='hpc_profile',
        ),
        migrations.RemoveField(
            model_name='topup',
            name='pool_allocation',
        ),
        migrations.AddField(
            model_name='topup',
            name='user_account',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='HARS.useraccount'),
            preserve_default=False,
        ),
    ]
