# Generated by Django 4.2 on 2024-10-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0015_remove_topup_pool_allocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_name', models.CharField(max_length=48, null=True)),
                ('pi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pool', to='HARS.instituteprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Pool_Topup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('rnd_time', models.DateTimeField(blank=True, null=True)),
                ('admin_time', models.DateTimeField(blank=True, null=True)),
                ('resource', models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU')], default='CPU', max_length=16, null=True)),
                ('hours', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('payment_mode', models.CharField(choices=[('Bank', 'Bank'), ('Project', 'Project')], default='Project', max_length=16, null=True)),
                ('project_no', models.CharField(blank=True, max_length=32, null=True)),
                ('budget_head', models.CharField(blank=True, max_length=32, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HARS.pool')),
            ],
        ),
        migrations.AddField(
            model_name='hpcprofile',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hpc_profile', to='HARS.pool'),
        ),
    ]
