# Generated by Django 4.2 on 2024-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0015_remove_topup_account_type_remove_topup_hpc_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='pool_allocation',
            field=models.BooleanField(default=False),
        ),
    ]
