# Generated by Django 4.2 on 2024-10-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0016_pool_pool_topup_hpcprofile_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Project', 'Project'), ('Pool', 'Pool')], default='Project', max_length=16, null=True),
        ),
    ]
