# Generated by Django 4.2 on 2024-11-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HARS', '0017_alter_application_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool_topup',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='hpcprofile',
            name='pool',
        ),
        migrations.AddField(
            model_name='topup',
            name='pool_allocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_mode',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Project', 'Project'), ('Pool', 'Pool')], default='Project', max_length=16),
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.DeleteModel(
            name='Pool_Topup',
        ),
    ]
