# Generated by Django 4.2.13 on 2024-06-25 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type_id', models.CharField(max_length=16)),
                ('admin', models.CharField(max_length=128, null=True)),
                ('project_no', models.CharField(max_length=32, null=True)),
                ('budget_head', models.CharField(max_length=16, null=True)),
                ('default_cpu_core_hours', models.IntegerField(default=0)),
                ('default_gpu_node_hours', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('pi_time', models.DateTimeField(blank=True, null=True)),
                ('rnd_time', models.DateTimeField(blank=True, null=True)),
                ('admin_time', models.DateTimeField(blank=True, null=True)),
                ('cpu_core_hours', models.IntegerField(default=20000)),
                ('gpu_node_hours', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=600)),
                ('payment_mode', models.CharField(choices=[('Bank', 'Bank'), ('Project', 'Project')], default='Project', max_length=16)),
                ('project_no', models.CharField(blank=True, max_length=16, null=True)),
                ('budget_head', models.CharField(blank=True, max_length=16, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HARS.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='HARSDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=32, unique=True)),
                ('value', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HPCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(max_length=128, null=True)),
                ('domain', models.CharField(max_length=128, null=True)),
                ('sub_domain', models.CharField(max_length=128, null=True)),
                ('software', models.CharField(max_length=128, null=True)),
                ('contact', models.CharField(blank=True, max_length=16, null=True)),
                ('gender', models.CharField(choices=[('-', '-------'), ('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default='M', max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, null=True)),
                ('department', models.CharField(max_length=48, null=True)),
                ('id_no', models.CharField(max_length=16, null=True)),
                ('designation', models.CharField(choices=[('S', 'Student'), ('PD', 'Post Doc'), ('F', 'Faculty'), ('PE', 'Project Employee'), ('SURGE', 'SURGE Student')], default='S', max_length=16, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=32, unique=True)),
                ('setting', models.CharField(max_length=32)),
                ('to', models.CharField(blank=True, max_length=256)),
                ('subject', models.CharField(blank=True, max_length=128)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=32, unique=True)),
                ('smtp_server', models.CharField(max_length=32)),
                ('smtp_port', models.PositiveIntegerField()),
                ('imap_server', models.CharField(max_length=32, null=True)),
                ('imap_port', models.PositiveIntegerField(null=True)),
                ('from_header', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('statistics_updated_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HARS.accounttype')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HARS.application')),
                ('institute_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HARS.instituteprofile')),
            ],
            options={
                'unique_together': {('institute_profile', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('pi_time', models.DateTimeField(blank=True, null=True)),
                ('rnd_time', models.DateTimeField(blank=True, null=True)),
                ('admin_time', models.DateTimeField(blank=True, null=True)),
                ('resource', models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU')], default='CPU', max_length=16, null=True)),
                ('hours', models.IntegerField(default=0)),
                ('units', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('payment_mode', models.CharField(choices=[('Bank', 'Bank'), ('Project', 'Project')], default='Project', max_length=16, null=True)),
                ('project_no', models.CharField(blank=True, max_length=32, null=True)),
                ('budget_head', models.CharField(blank=True, max_length=32, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HARS.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=32)),
                ('used', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HARS.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.CharField(max_length=128, null=True)),
                ('hpc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HARS.hpcprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_per_core_hour', models.FloatField(default=0.0)),
                ('gpu_per_node_hour', models.FloatField(default=0.0)),
                ('cpu_unit_recharge', models.IntegerField(default=0)),
                ('gpu_unit_recharge', models.IntegerField(default=0)),
                ('account_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HARS.accounttype')),
            ],
        ),
        migrations.AddField(
            model_name='hpcprofile',
            name='institute_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_profile', to='HARS.instituteprofile'),
        ),
        migrations.AddField(
            model_name='hpcprofile',
            name='pi_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi', to='HARS.instituteprofile'),
        ),
        migrations.AddField(
            model_name='application',
            name='hpc_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HARS.hpcprofile'),
        ),
    ]
